spring:
  datasource:
    url: jdbc:postgresql://dpg-cjutgi7hdsdc73f0nhf0-a.oregon-postgres.render.com:5432/db_dvd9 #jdbc:postgresql://localhost:5432/postgres
    username: db #postgres
    password: 1spvkuGTmz2nef6YSHbg0QeSGfKjfk5q #postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect