spring:
  datasource:
#    url: jdbc:postgresql://dpg-cjutgi7hdsdc73f0nhf0-a.oregon-postgres.render.com:5432/db_dvd9
#    username: db
#    password: 1spvkuGTmz2nef6YSHbg0QeSGfKjfk5q
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: fcEE4b3TXpm139pBjDFKvIlb4jcliKZI6i4L8ekkS9CQlXyt40
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect